version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8095:15672"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  collector:
    image: iot-collector-app
    depends_on:
    - rabbitmq
    - mongo
    - pipeline
    - mongo-client
    - web-client-be
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    restart:
      unless-stopped

  pipeline:
    image: iot-pipeline-app
    depends_on:
    - rabbitmq
    - mongo
    environment:
      - "RABBIT_HOST=rabbitmq"
      - "BATCH_SIZE=1"
    restart:
      always

  mongo-client:
    image: mongo-client-app
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - "RABBIT_HOST=rabbitmq"
      - "MONGO_HOST=mongo"
      - "MONGO_PORT=27017"
    restart:
      always

  web-client-be:
    image: iot-client-be
    depends_on:
      - rabbitmq
    environment:
      - "RABBIT_HOST=rabbitmq"
    ports:
      - 3000:3000
    restart:
      always

  web-client:
    image: iot-web-client
    ports:
      - 80:80
    restart:
      always
